import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ThemeProvider } from "./context/ThemeContext";
import TopMore from "./components/TopMore";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mikey's",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Navbar />
          <TopMore />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
